### ISSUE TITLE
zmq 3.1

### ISSUE THREAD

**Issue by schmurfy** [andrewvc/em-zeromq#10]
This is not really an issue, more an open question :)

I started using zmq on a work project and for that I started straight with zeromq 3.1 which is in beta state right now, I have a local branch where I first tried to keep compatibility with other zmq releases but in the end I just dropped it which cleaned some edges.
(in 3.1 some function names changed in the C api, some constants disappeared, other appeared)

My question is what strategy should we use the gem ?
We can do like ffi-rzmq and support all zeromq versions or we can decide that newer releases support the latest zeromq version (out of beta of course), I am personnaly in favor of the last choice given the fact that old versions of the gem will still remain if someone want to use another zeromq version, we just need to document it in the README.

**Comment by schmurfy** [comment]
@andrewc, any opinion on this ?

**Comment by andrewvc** [comment]
Hi schmurfy, unfortunately, I pretty much just don't have the time to maintain this gem anymore. 

I no longer actively use it, so I'm looking for a new maintainer.

You're at the top of my list for a candidate, your thoughts?

**Comment by schmurfy** [comment]
I was not using it until now but will soon use it on a real project ^^
so I can take care of it sure !

**Comment by schmurfy** [comment]
@deepfryed if you plan to use the gem what is your opinion on this ?

I will use 3.1 and so I plan to focus my work on 3.1 to avoid wasting resources on keeping 2.1 compatibility (3.1 is really close to becoming the new stable version anyway)

**Comment by deepfryed** [comment]
A few things have changed between 2.1 & 3.1 but I think you can maintain both in a clean fashion. 
1. abstract out the common logic 
2. define the version specific parts as mixins - since they define the version specific behaviour.
3. allow the user to load em-zeromq/version2.1  or em-zeromq/version3.1 

I do intend to keep using 2.1 in the immediate future since its been very stable thus far.

**Comment by schmurfy** [comment]
3.1 changes are:
- some getsockopt/setsockopt were added, other were removed and other changed name
- some functions changed name/signature

3 is not necessary we can switch on the fly like ffi-rzmq does depending on the version returned by the C api

**Comment by CootCraig** [comment]
Hi schmurfy

I'm running into zeromq 2.x / 3.x problems.  I am trying out em-zeromq for the first time.  Maybe I can be of some help fixing and testing this. FWIW my current production target is Windows Server 2008 with RubyInstaller Ruby 1.9.3-p194

**Comment by schmurfy** [comment]
I am not currently using it in production but in testing em-zeromq works well with zeromq 2.x but I did not do extensive testing with 3.x.
What sort of problems are you running into ?

**Comment by schmurfy** [comment]
closing this since it is now outdated.
