### ISSUE TITLE
undefined method `errno' for ZMQ:Module

### ISSUE THREAD

**Issue by gamemachine** [andrewvc/em-zeromq#11]
NoMethodError: undefined method `errno' for ZMQ:Module
  getsockopt_with_raise at /home/marvel/.rvm/gems/jruby-1.6.5/gems/em-zeromq-0.2.2/lib/em-zeromq/rzmq_compat.rb:25

This seems kind of strange to me.  the zeromq gem say's to check ZMQ.errno like you are doing, but errno is defined in ZMQ::Util and only included in specific zeromq classes, so it's not accessible as ZMQ.errno from anywhere, you have to specifically include ZMQ::Util within the namespace you want to call it from.

Looks like the quick fix is to just call ZMQ::Util.errno

**Comment by chuckremes** [comment]
i've been messing around with the pre-1.0 api for ffi-rzmq which is used by em-zeromq. It's entirely possible that ZMQ.errno used to exist and I moved it to Util.

**Comment by andrewvc** [comment]
Unfortunately, I don't have the time to maintain this gem actively, if you'd like to help out and send in a (tested) patch, that'd be much appreciated.

**Comment by schmurfy** [comment]
We should'nt use "~>" for the dependency until the api is stable, I wil try fixing that this week end. Until now a quick fix is to use the gem with ffi-rzmq 0.9.3 which is the version I am currently using so hopefully it works with it :)
