### ISSUE TITLE
Inproc-only sockets doesn't work

### ISSUE THREAD

**Issue by prepor** [andrewvc/em-zeromq#2]
Hello!

Based on your example: http://pastie.org/private/fbfwo6lzgvhcnkhblkcdzq

<pre>
  => ........
</pre>

BUT: http://pastie.org/private/42m4yamynxa0krczhbrgtq (with pull_socket.connect('ipc:///tmp/a') )

<pre>
  => ._._._._._._._._._._._._
</pre>

Why?

This is not my only problem, but the main now :)

**Comment by andrewvc** [comment]
hmmm, works for me. Try updating to the newest em-zeromq off github, and see if the problem's still there. If so, what platform/ruby are you on?

**Comment by prepor** [comment]
With em-zeromq and eventmachine from head works.

Thanks!

**Comment by andrewvc** [comment]
Fixed!
