### ISSUE TITLE
[Question]  Usage Warning Garbage Collector

### ISSUE THREAD

**Issue by tdantas** [andrewvc/em-zeromq#24]
I have one question that is poking my head for long time.
Given the code below, comparing with your usage warning GC, is supposed that **gc** variable should be collected when the GC run. right ?

```
require 'eventmachine'
require 'objspace'

EM.run do 
  gc = Object.new
  puts gc.object_id
  ObjectSpace.define_finalizer(gc, proc {|id| puts "Collected #{id}" })
  EM.add_timer(1) {  puts "Starting GC"; GC.start; }
end
```

The curious part is that the GC will never reclaim **gc** object, I don't know why ?
Do you know ?
Before run the snippet above, I thought that the **gc** will be collected without any doubts like the **Usage Warning**

The snippet below, the **_Object.new**_  _without root_ will be reclaimed properly.

```
require 'eventmachine'
require 'objspace'

EM.run do 
  ObjectSpace.define_finalizer(Object.new, proc {|id| puts "Collected #{id}" })
  EM.add_timer(1) {  puts "Starting GC"; GC.start; }
end
```

**Comment by mloughran** [comment]
This hasn't anything to do with em-zeromq tbh... but the reason `gc` is not collected in the top example is that it never goes out of scope while the eventmachine reactor is running (ruby is in the EM.run block)

**Comment by schmurfy** [comment]
as he said :)

as I understand it (I was originally bitten by this before we added the warning):
if you create an object but do not bind it to a variable when the GC run it will destroy it, it is obvious when you think about it but the way the example were initially written triggered this issue.

This is usually not really an issue since you don't really write code like that unless you are testing something, when you write the real code with classes everything will be properly bound as it should.

**Comment by tdantas** [comment]
Hi Guys,
Thanks for the feedback @schmurfy @mloughran 

It is quite interesting.
look the code below

```
  1 require 'eventmachine'
  2 require 'objspace'
  3
  4 EM.run do
  5
  6   10.times do
  7     x = Object.new
  8     ObjectSpace.define_finalizer(x, proc {|id| puts "Collected #{id}" })
  9   end
 10
 11   ObjectSpace.define_finalizer(Object.new, proc {|id| puts "Collected without binding #{id}" })
 12
 13
 14   EM.add_timer(1) {  puts "Starting GC"; GC.start; }
 15 end

```

I' am leaking on purpose (**line 6 - 9**) creating 10 times the same object ( malloc ) and bounded all to the same variable **x**.

What point am I missing ? All 9 objects shouldn't be reclaimed ?
Line 11 the object will be collected as soon as GC.start finish.

**Comment by tdantas** [comment]
Sorry Guys,
I figured it out the problem with my last comment.
The proc will capture the lexical scope and create a closure with the x variable.

The code below works perfect and will be collected properly.

Thanks for your time !
cya

```
require 'eventmachine'
require 'objspace'

class Destructor
  def self.on_collected
    proc {|id| puts "Collected #{id}" }   
  end
end
EM.run do

  10.times do
    x = Object.new
     ObjectSpace.define_finalizer(x, Destructor.on_collected)
   end

   ObjectSpace.define_finalizer(Object.new, proc {|id| puts "Collected without binding #{id}" })

   EM.add_timer(1) {  puts "Starting GC"; GC.start; }
end
```
