### ISSUE TITLE
ROUTER and DEALER are switched

### ISSUE THREAD

**Issue by danielwaterworth** [andrewvc/em-zeromq#7]
http://api.zeromq.org/2-1:zmq-socket defines ROUTER to be synonymous with XREP and DEALER to be synonymous with XREQ, however in em-zeromq:

```
ZMQ::ROUTER == ZMQ::XREQ and ZMQ::DEALER == ZMQ::XREP
```

**Comment by chuckremes** [comment]
I believe this issue was due to a bug in the ffi-rzmq gem. That has been fixed in the latest update. Upgrade your ffi-rzmq gem to 0.8.2 and try again.

**Comment by andrewvc** [comment]
Yes, indeed it is. I'm going to re-release this gem tonight with that version number enforced.

**Comment by danielwaterworth** [comment]
Thanks, that has indeed fixed it.

**Comment by andrewvc** [comment]
Hmmm, did a little work bringing the gem up to date with the router / dealer rename and noticed there's a failing spec. I'm going to delay a release till I figure that out.
