### ISSUE TITLE
failing specs

### ISSUE THREAD

**Issue by schmurfy** [andrewvc/em-zeromq#8]
There are two failing tests in the master branch, is it normal ?

**Comment by cremes** [comment]
It depends on which 0mq version you are testing against. If you have 2.1.10 loaded, there should be no failures. If you have 3.x loaded, there are 2 failures (known bugs in 3.x).

If it is 2.1.10, please give me more information.

**Comment by chuckremes** [comment]
Oops, my apologies. I thought this was another issue against ffi-rzmq. Sorry!

**Comment by schmurfy** [comment]
I get the same failures with 2.1.9 and 2.1.10, I just commited some changes but the failures were already there before so I am sure I did not introduced them, Here is the failing tests:

Failures:

  1) EventMachine::ZeroMQ sending/receiving a single message via Router/Dealer should receive the message intact on the dealer
     Failure/Error: @results[:dealer_hndlr].received.should_not be_empty
       expected empty? to return false, got true
     # ./spec/router_dealer_spec.rb:69:in `block (3 levels) in <top (required)>'

  2) EventMachine::ZeroMQ sending/receiving a single message via Router/Dealer the router should be echoed its original message
     Failure/Error: @results[:router_hndlr].received.should_not be_empty
       expected empty? to return false, got true
     # ./spec/router_dealer_spec.rb:75:in `block (3 levels) in <top (required)>'

**Comment by vishnugopal** [comment]
I've got zeromq 2.1.10 & the same issue!
