### ISSUE TITLE
em-zeromq 0.2.1 on rubygems.org not working with ffi-rzmq 0.9.0

### ISSUE THREAD

**Issue by sepastian** [andrewvc/em-zeromq#9]
Hi Andrew, 

Could you please update the em-zeromq gem on RubyGems.org?

When running `example/simple.rb` using em-zeromq 0.2.1 from RubyGems.org an exception is thrown because ffi-rzmq is missing an argument. The problem is gone when using github/master (although the version is still 0.2.1?).

A workaround is `bundle install` to get the github version. However, when running `bundle exec` is giving me a segmentation fault. So that doen't really solve the problem.

My configuration:
- em-zeromq (0.2.1)
- ffi-rzmq (0.9.0)
- zmq (2.1.4)
- ffi-rzmq (0.9.0)
- ruby 1.9.2p180 (2011-02-18 revision 30909) [i686-linux]
- rvm 1.6.20 by Wayne E. Seguin (wayneeseguin@gmail.com)

The exception thrown is

```/home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/ffi-rzmq-0.9.0/lib/ffi-rzmq/socket.rb:387:in`getsockopt': wrong number of arguments (1 for 2) (ArgumentError)
        from /home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/em-zeromq-0.2.1/lib/em-zeromq/context.rb:48:in `create'
        from /home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/em-zeromq-0.2.1/lib/em-zeromq/context.rb:22:in`bind'
        from server.rb:19:in `block in <main>'
        from /home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in`call'
        from /home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in `run_machine'
        from /home/sebastian/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in`run'
        from server.rb:15:in `<main>'

```
```

**Comment by schmurfy** [comment]
I commited the fix to make em-zeromq works with latest ffi-rzmq but I let andwrew handle the versioning that is why the version did not changed ^^
The api changed heavily in ffi-rzmq 0.9 and the gem was not locked to a specific version.

**Comment by andrewvc** [comment]
Apologies for the delayed release. I just released version 0.2.2 which should fix this.

**Comment by sepastian** [comment]
Cool, thanks for the quick fix.
